name: finly-backend
services:
  finly:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./.db:/app/database
      - ~/code/ssl:/app/ssl
      - ./html:/app/html
      - ./sql:/app/sql
    environment:
      - DATABASE_URL=sqlite:///app/database/main.db
      - JWT_ENC_PATH=/app/ssl/jwt.pem
      - JWT_DEC_PATH=/app/ssl/jwt.pub
      - TLS_KEY_PATH=/app/ssl/priv.key
      - TLS_CERT_PATH=/app/ssl/certificate.crt
      - SESSION_DB_DDL_SCRIPT_PATH=/app/sql/init_session_db.sql
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=us-east-1

